export const venues = [
    'Narendra Modi Stadium, Motera, Ahmedabad',
    'M.Chinnaswamy Stadium, Bengaluru',
    'MA Chidambaram Stadium, Chepauk, Chennai',
    'Wankhede Stadium, Mumbai',
    'Eden Gardens, Kolkata',
    'Arun Jaitley Stadium, Delhi',
    'Himachal Pradesh Cricket Association Stadium, Dharamsala',
    'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
    'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
    'Sawai Mansingh Stadium, Jaipur',
    'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
    'Barsapara Cricket Stadium, Guwahati',
    'Brabourne Stadium, Mumbai',
    'Dr DY Patil Sports Academy, Navi Mumbai',
    'Maharashtra Cricket Association Stadium, Pune',
    'Dubai International Cricket Stadium',
    'Sharjah Cricket Stadium',
    'Sheikh Zayed Stadium, Abu Dhabi',
    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam',
    'Holkar Cricket Stadium, Indore',
    'Green Park, Kanpur',
    'Saurashtra Cricket Association Stadium, Rajkot',
    'Shaheed Veer Narayan Singh International Stadium, Raipur',
    'JSCA International Stadium Complex, Ranchi',
    'Sardar Patel (Gujarat) Stadium, Motera, Ahmedabad',
    'Barabati Stadium, Cuttack',
    'Dr DY Patil Sports Academy, Mumbai',
    'Nehru Stadium, Kochi',
    'Vidarbha Cricket Association Stadium, Jamtha, Nagpur',
    'The Wanderers Stadium, Johannesburg',
    'SuperSport Park, Centurion',
    'Kingsmead, Durban',
    'Mangaung Oval, Bloemfontein',
    'St George\'s Park, Port Elizabeth',
    'Diamond Oval, Kimberley',
    'Buffalo Park, East London',
    'Newlands, Cape Town'
  ];
  